# landscape short name
landscapeName: ossf 
# Update with your membership structure
landscapeMemberClasses:
  - name: Premier Membership
    category: Premier
  - name: General Membership
    category: General
  - name: Associate Membership
    category: Associate
  - name: OpenSSF Member
    category: Founding
# SF Project record ID for your project
project: a092M00001Iw46JQAR # OpenSSF
# Name of category for members 
landscapeMemberCategory: OpenSSF Members
