global:
  name: OpenSSF Landscape
  short_name: OpenSSF
  repo: ossf/ossf-landscape
  website: https://landscape.openssf.org
  short_domain: l.openssf.org
  company_url: https://openssf.org
  email: info@openssf.org
  self: https://www.crunchbase.com/organization/linux-foundation
  slack_channel: T08PSQ7BQ/BM7M5TKSR/Xjll8jWb2cgpO7aOCGxUtebU
  meta:
    title: OpenSSF Landscape
    fb_admin: alex.contini.94
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: '@todogroup'
    google_site_verification: u_xqWIf8_EzRP4UF92px16rTSoIP49D_g9i7M-4rXds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: OpenSSF Members
  flags:
    companies: OpenSSF Members
twitter:
  search: landscape.openssf.org
  url: https://landscape.openssf.org
  text: OpenSSF Landscape
relation:
  label: OpenSSF Relation
  url: ossf
  values:
    - id: hosted
      label: OpenSSF Working Groups
      children:
        - id: workinggroups
          label: OpenSSF Working Group
          prefix: OpenSSF
          tag: Working Group
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: OpenSSF Working Group
          big_picture_color: rgb(24,54,114)
        - id: incubating
          label: OpenSSF Project
          prefix: OpenSSF
          tag: OpenSSF Project
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: OpenSSF Project
          big_picture_color: rgb(24,54,114)          
    - id: company
      label: OpenSSF Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: OpenSSF Member Products/Projects
      tag: OpenSSF Member
    - id: false
      label: Non-OpenSSF Member Products/Projects
      url: 'no'
membership:
  Premier:
    name: Premier
    label: Premier Member
    funding: Premier
  General:
    name: General
    label: General Member
    funding: General
  Associate:
    name: Associate
    label: Associate Member
    funding: Associate
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>OpenSSF Landscape</h1> The OpenSSF landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/?utm_source=ospo_landscape&utm_medium=web&utm_campaign=kccnceu20
    image: /images/info1.jpg
    title: Kubecon + CloudNativeCon Europe 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: OpenSSF Landscape
    fullscreen_header: See the interactive landscape at l.openssf.org
    elements:
      - type: VerticalCategory
        category: OpenSSF Members
        width: 650
        height: 400
        top: 0
        left: 0
        color: rgb(103,66,18)
        fit_width: true
      - type: LandscapeInfo
        width: 310
        height: 150
        top: 0
        left: 665
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the OpenSSF community, and also shows the member organizations of the OpenSSF.
            top: 45
            left: 140
            right: 10
            font_size: 10
          - type: image
            image: qr.svg
            top: 10
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.openssf.org
            top: 95
            left: 10
            font_size: 18
          - type: image
            image: left-logo.svg
            width: 90
            right: 105
            top: 10
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 90
            right: 10
            top: 10
            title: OpenSSF Logo
  sigstore:
    tab_index: 2
    name: Sigstore
    url: sigstore
    short_name: sigstore
    title: SigStore Landscape
    fullscreen_header: Header for a sigstore
    category: Sigstore
    elements:
      - type: HorizontalCategory
        category: Architecture/Spec
        rows: 1
        width: 220
        height: 200
        top: 5
        left: 5
        color: rgb(179,208,231)
        is_large: true    
      - type: HorizontalCategory
        category: Projects
        rows: 1
        width: 280
        height: 200
        top: 5
        left: 235
        color: rgb(237,106,91)
        is_large: true
      - type: HorizontalCategory
        category: Deployments
        rows: 1
        width: 320
        height: 200
        top: 5
        left: 530
        color: rgb(103,66,18)
        is_large: true
      - type: HorizontalCategory
        category: Integrations
        rows: 2
        width: 550
        height: 200
        top: 215
        left: 5
        color: rgb(221,236,197)
        is_large: true
      - type: HorizontalCategory
        category: Language Clients
        rows: 2
        width: 270
        height: 200
        top: 215
        left: 580
        color: rgb(46,47,113)
        is_large: true        
      - type: HorizontalCategory
        category: Signed With
        rows: 2
        width: 600
        height: 200
        top: 425
        left: 5
        color: rgb(244,190,55)
        is_large: true
      - type: HorizontalCategory
        category: Case Studies
        rows: 2
        width: 220
        height: 200
        top: 425
        left: 630
        color: rgb(17,115,115)
        is_large: true
test:
  header: OpenSSF Landscape
  section: OpenSSF Members
  logo: google-llc.svg
prerender:
  members: /card-mode?category=open-ssf-members&grouping=category&embed=yes&style=borderless
export: {}
